buildscript {
    repositories {
        maven { url = 'https://maven.firstdark.dev/releases' }
        mavenCentral()
        gradlePluginPortal()
        flatDir {
            dirs 'libs'
        }
    }
    dependencies {
        classpath 'com.hypherionmc.modutils:modpublisher:2.2.1'
    }
}

plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.4'
}

apply plugin: 'com.hypherionmc.modutils.modpublisher'

if (project.file('../gradletools.gradle').exists()) {
    apply from: '../gradletools.gradle'
} else {
    apply from: 'https://raw.githubusercontent.com/McJtyMods/MultiWorkspace/1.21_neo/gradletools.gradle'
}

group = "com.github.synthlax"
archivesBaseName = "lostcitiesfork"
java.toolchain.languageVersion = JavaLanguageVersion.of(21)

if (System.getenv('BUILD_NUMBER') != null) {
    version += "-${System.getenv('BUILD_NUMBER')}"
}

repos()
at()
runs()
jars()

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

dependencies {
    mc()
    jei()
    top()
    implementation files('libs/c2me-neoforge-mc1.21.1-0.3.0+alpha.0.93.jar')
    implementation files('libs/DistantHorizons-3.0.3-b-1.21.1-fabric-neoforge.jar')
}


subsystems {
    parchment {
        minecraftVersion = "${parchment_minecraft_version}"
        mappingsVersion = "${parchment_version}"
    }
}


task apiJar(type: Jar) {
    archiveClassifier = "api"
    from(sourceSets.main.output) {
        include "synthlax/lostcitiesfork/api/**"
    }
}

artifacts {
    archives apiJar
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java
        artifact apiJar

        artifactId = project.archivesBaseName
        pom {
            name = 'LostCitiesFork'
            description = 'Lost Cities Fork'
            scm {
                url = 'https://github.com/synthlax/LostCitiesFork-1.21.1'
                connection = 'scm:git:git@github.com:synthlax/LostCitiesFork-1.21.1.git'
                developerConnection = 'scm:git:git@github.com:synthlax/LostCitiesFork-1.21.1.git'
            }
            licenses {
                license {
                    name = 'MIT'
                    distribution = 'repo'
                }
            }
            developers {
                developer {
                    id = 'McJty'
                    name = 'McJty'
                    roles = ['developer']
                }
                developer {
                    id = 'Synthlax'
                    name = 'Synthlax'
                    roles = ['developer']
                }
            }
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                name = 'local'
                url = 'file://' + System.getenv('local_maven')
            }
        }
    }
}

