modLoader="javafml"
license="MIT License https://github.com/McJtyMods/LostCities/blob/1.21_neo/LICENSE"
loaderVersion="[2,)"
displayURL="https://github.com/synthlax/LostCitiesFork-1.21.1"
#logoFile="examplemod.png" #optional
credits="Thanks for this original mod goes to McJty" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="lostcitiesfork"
version="${file.jarVersion}"
displayName="LostCitiesFork"
#updateJSONURL="http://myurl.me/" #optional
description='''
Generate cities all over the world
'''
[[dependencies.lostcitiesfork]]
    modId="neoforge"
    type="required"
    versionRange="[21.0,)"
    ordering="NONE"
    side="BOTH"
